Page({
    data:{
        sellFouthScrollBooks:[
            {
              "src":"http://www.gether.cn/zhuanzhuan/image/sellFouthImg/book1.jpg",
              "text1":"活着",
              "text2":"余华",
              "price":"3.77",
              "discount":"2.9折"
            },
            {
              "src":"http://www.gether.cn/zhuanzhuan/image/sellFouthImg/book2.jpg",
              "text1":"至此剧终",
              "text2":"墨宝非宝",
              "price":"6.61",
              "discount":"2.9折"
            },
        ],
        icons:
        [
            {
                "img":"http://www.gether.cn/zhuanzhuan/image/sellFouthImg/btn1.png",
                "text":"扫描图书的条形码"
            },
            {
                "img":"http://www.gether.cn/zhuanzhuan/image/sellFouthImg/btn2.png",
                "text":"填写地址提交订单"
            },
            {
                "img":"http://www.gether.cn/zhuanzhuan/image/sellFouthImg/btn3.png",
                "text":"快递上门转转包邮"
            },
            {
                "img":"http://www.gether.cn/zhuanzhuan/image/sellFouthImg/btn4.png",
                "text":"转转收货打款进账"
            },
        ],
    },
    sellFouthScrollBtn:function(){
        this.setData({
          sellFouthHide:!this.data.sellFouthHide
        })
    },
})