Page({
    data:{
        sellSecondBtnIconBoxs:
        [
            {
              "src":"http://www.gether.cn/zhuanzhuan/image/sellSecondImg/icon1.png",
              "text":"免费上门取件"
            },
            {
              "src":"http://www.gether.cn/zhuanzhuan/image/sellSecondImg/icon2.png",
              "text":"数据安全护航"
            },
            {
              "src":"http://www.gether.cn/zhuanzhuan/image/sellSecondImg/icon3.png",
              "text":"千万买家竞价"
            },
            {
              "src":"http://www.gether.cn/zhuanzhuan/image/sellSecondImg/icon4.png",
              "text":"极速打款"
            },
        ],
        sellSecondTopBottomTexts:
        [
            {
                "img":"http://www.gether.cn/zhuanzhuan/image/sellSecondImg/one.png",
                "text":"24小时成交",
            },
            {
                "img":"http://www.gether.cn/zhuanzhuan/image/sellSecondImg/two.png",
                "text":"远高回收价",
            },
            {
                "img":"http://www.gether.cn/zhuanzhuan/image/sellSecondImg/three.png",
                "text":"0沟通0纠纷",
            }
        ],
        sellSecondBottomIconBoxOuts:
        [
            {
              "id":0,
              "img":"http://www.gether.cn/zhuanzhuan/image/sellSecondImg/btn1.png",
              "text1":"1.市场回收价作为预付款打给您",
              "text2":"顺丰上门取件后获得预付款"
            },
            {
              "id":1,
              "img":"http://www.gether.cn/zhuanzhuan/image/sellSecondImg/btn2.png",
              "text1":"2.没有中间商倒卖赚差价",
              "text2":"以市场回收价为起拍价竞拍,全款都给您"
            },
            {
              "id":2,
              "img":"http://www.gether.cn/zhuanzhuan/image/sellSecondImg/btn3.png",
              "text1":"3.海量买家帮您拍出超高价",
              "text2":"价格更公正,竞拍更透明"
            }
        ],
    }
})