Page({
    data:{
        sellFirstDivs:
        [
            {
                "Simg":"http://www.gether.cn/zhuanzhuan/image/sellFirstImg/image1.png",
                "Stext":"闲置的电脑"
            },
            {
                "Simg":"http://www.gether.cn/zhuanzhuan/image/sellFirstImg/image2.png",
                "Stext":"过时的手机"
            },
            {
                "Simg":"http://www.gether.cn/zhuanzhuan/image/sellFirstImg/image3.png",
                "Stext":"换掉的耳机"
            },
            {
                "Simg":"http://www.gether.cn/zhuanzhuan/image/sellFirstImg/image4.png",
                "Stext":"不穿的衣服"
            },
            {
                "Simg":"http://www.gether.cn/zhuanzhuan/image/sellFirstImg/image5.png",
                "Stext":"换季的包包"
            },
            {
                "Simg":"http://www.gether.cn/zhuanzhuan/image/sellFirstImg/image6.png",
                "Stext":"囤多的化妆品"
            },
            {
                "Simg":"http://www.gether.cn/zhuanzhuan/image/sellFirstImg/image7.png",
                "Stext":"占地儿的沙发"
            },
            {
                "Simg":"http://www.gether.cn/zhuanzhuan/image/sellFirstImg/image8.png",
                "Stext":"多余的洗衣机"
            },
            {
                "Simg":"http://www.gether.cn/zhuanzhuan/image/sellFirstImg/image9.png",
                "Stext":"宝宝的玩具"
            },
        ],
        sellFirstDiv2s:
        [
            {
                "text":"1.只有通过该活动页面成功发布商品后,才可以获得红包奖励,通过其他途径发布商品,不享受该机会;",
            },
            {
                "text":"2.每个用户限得1个红包,多次发布不会累计发放红包;",
            },
            {
                "text":"3.红包一般在24小时内完成发放,可在个人中心-我的红包列表查看;",
            },
            {
                "text":"4.红包不可兑换现金;",
            },
            {
                "text":"5.红包可用于购买发布6小时以上的商品,近6小时内发布的商品不可用;",
            },
            {
                "text":"6.通过活动发布的商品需要通过审核,方可获得红包;发布虚假、低质商品不可获得红包;",
            },
            {
                "text":"7.活动期间，如发现通过非正常途径获得红包,转转有权利追回所得红包;",
            },
            {
                "text":"8.在法律允许的范围内,转转拥有最终解释权。"
            },
        ],
    }
})