Page({
    data:{
        thirdTab:0,
        sellThirdMorestate:0,
        thirdOutShowState:1,
        sellThirdFixedBottomBtnState:1,
        thirdSellTopicStyleName1:{thirdSellTopicStyleName:"旧衣回收流程"},
        thirdSellTopicStyleName2:{thirdSellTopicStyleName:"环保达人"},
        thirdSellTopicStyleName3:{thirdSellTopicStyleName:"旧衣现状"},
        thirdSellTopicStyleName4:{thirdSellTopicStyleName:"旧衣处理"},
        thirdSellTopicStyleName5:{thirdSellTopicStyleName:"回收问答"},
        sellThirdTopIconLefts:
        [
            {
              "src":"http://www.gether.cn/zhuanzhuan/image/sellThirdImg/topbtn1.png",
              "text":"免费上门"
            },
            {
              "src":"http://www.gether.cn/zhuanzhuan/image/sellThirdImg/topbtn2.png",
              "text":"现金奖励"
            },
            {
              "src":"http://www.gether.cn/zhuanzhuan/image/sellThirdImg/topbtn3.png",
              "text":"优惠卷"
            },
            {
              "src":"http://www.gether.cn/zhuanzhuan/image/sellThirdImg/topbtn4.png",
              "text":"绿色环保"
            },
            {
              "src":"http://www.gether.cn/zhuanzhuan/image/sellThirdImg/topbtn5.png",
              "text":"热心公益"
            },
        ], 
        sellThirdScrollChangeBoxCenterLeftItems:[{},{},{}],
        sellThirdScrollChangeBoxCenterLeftItemFlexs:
        [
            {
              "img":"http://www.gether.cn/zhuanzhuan/image/user-image/user-image1.jpg",
              "name":"User-1",
              "place":"成都市",
              "kg":"80kg",
              "img2":"http://www.gether.cn/zhuanzhuan/image/sellThirdImg/img4.png"
            },
            {
              "img":"http://www.gether.cn/zhuanzhuan/image/user-image/user-image2.jpg",
              "name":"User-2",
              "place":"杭州市",
              "kg":"70kg",
              "img2":"http://www.gether.cn/zhuanzhuan/image/sellThirdImg/img4.png"
            },
            {
              "img":"http://www.gether.cn/zhuanzhuan/image/user-image/user-image3.jpg",
              "name":"User-3",
              "place":"重庆市",
              "kg":"60kg",
              "img2":"http://www.gether.cn/zhuanzhuan/image/sellThirdImg/img4.png"
            },
        ],
        sellThirdScrollChangeBoxCenterRightBoxs:
        [
            {
              "img1":"http://www.gether.cn/zhuanzhuan/image/user-image/user-image1.jpg",
              "name":"user-1",
              "place":"成都市",
              "kg":"223020kg",
              "img2":"http://www.gether.cn/zhuanzhuan/image/sellThirdImg/img1.png"
            },
            {
              "img1":"http://www.gether.cn/zhuanzhuan/image/user-image/user-image2.jpg",
              "name":"user-2",
              "place":"杭州市",
              "kg":"203020kg",
              "img2":"http://www.gether.cn/zhuanzhuan/image/sellThirdImg/img2.png"
            },
            {
              "img1":"http://www.gether.cn/zhuanzhuan/image/user-image/user-image3.jpg",
              "name":"user-3",
              "place":"北京市",
              "kg":"202920kg",
              "img2":"http://www.gether.cn/zhuanzhuan/image/sellThirdImg/img3.png"
            },
            {
              "img1":"http://www.gether.cn/zhuanzhuan/image/user-image/user-image4.jpg",
              "name":"user-4",
              "place":"重庆市",
              "kg":"202820kg",
              "img2":"http://www.gether.cn/zhuanzhuan/image/sellThirdImg/img4.png"
            },
            {
              "img1":"http://www.gether.cn/zhuanzhuan/image/user-image/user-image5.jpg",
              "name":"user-5",
              "place":"泸州市",
              "kg":"202720kg",
              "img2":"http://www.gether.cn/zhuanzhuan/image/sellThirdImg/img4.png"
            },
            {
              "img1":"http://www.gether.cn/zhuanzhuan/image/user-image/user-image6.jpg",
              "name":"user-6",
              "place":"南充市",
              "kg":"202620kg",
              "img2":"http://www.gether.cn/zhuanzhuan/image/sellThirdImg/img4.png"
            },
            {
              "img1":"http://www.gether.cn/zhuanzhuan/image/user-image/user-image7.jpg",
              "name":"user-7",
              "place":"攀枝花",
              "kg":"202520kg",
              "img2":"http://www.gether.cn/zhuanzhuan/image/sellThirdImg/img4.png"
            },
            {
              "img1":"http://www.gether.cn/zhuanzhuan/image/user-image/user-image1.jpg",
              "name":"user-8",
              "place":"广元市",
              "kg":"202420kg",
              "img2":"http://www.gether.cn/zhuanzhuan/image/sellThirdImg/img4.png"
            },
            {
              "img1":"http://www.gether.cn/zhuanzhuan/image/user-image/user-image2.jpg",
              "name":"user-9",
              "place":"广元市",
              "kg":"202320kg",
              "img2":"http://www.gether.cn/zhuanzhuan/image/sellThirdImg/img4.png"
            },
            {
              "img1":"http://www.gether.cn/zhuanzhuan/image/user-image/user-image3.jpg",
              "name":"user-10",
              "place":"广元市",
              "kg":"202220kg",
              "img2":"http://www.gether.cn/zhuanzhuan/image/sellThirdImg/img4.png"
            },
        ],
        sellThirdBottomClothes1BoxOuts:
        [
            {
              "img":"http://www.gether.cn/zhuanzhuan/image/sellThirdImg/old1.png",
              "text1":"浪费资源",
              "text2":"我国每年产生2600万吨废旧纺织品,综合利用率却不足10%",
            },
            {
              "img":"http://www.gether.cn/zhuanzhuan/image/sellThirdImg/old2.png",
              "text1":"环保节能",
              "text2":"如果每年产生的废旧纺织品能全部得到循环利用，就可以节约2400万吨原油，相当于半个大庆油田",
            },
            {
              "img":"http://www.gether.cn/zhuanzhuan/image/sellThirdImg/old3.png",
              "text1":"供大于求",
              "text2":"我国贫困山区旧衣捐赠需求逐渐减弱，频次大幅降低。",
            },
        ],
        sellThirdBottomClothes2BoxOuts:
        [
            {
              "img":"http://www.gether.cn/zhuanzhuan/image/sellThirdImg/old4.png",
              "text1":"环保再生",
              "text2":"我国每年产生2600万吨废旧纺织品,综合利用率却不足10%",
              "text3":"约占75%",
            },
            {
              "img":"http://www.gether.cn/zhuanzhuan/image/sellThirdImg/old5.png",
              "text1":"公益捐赠",
              "text2":"将符合捐赠标准的较新、质量较好的衣物进行清洗消毒，捐赠到有需有的贫困山区或公益组织及个人",
              "text3":"约占10%",
            },
            {
              "img":"http://www.gether.cn/zhuanzhuan/image/sellThirdImg/old6.png",
              "text1":"慈善商店",
              "text2":"将符合标准的夏装经过清洗消毒，交给相关外贸公司输出到非洲等凭困国家，所得资金做为公益金。",
              "text3":"约占15%",
            },
        ],
        sellThirdBottomAnswers:
        [
            {
              "text":"我要怎么参与旧衣回收呢?"
            },
            {
              "text":"旧衣回收运费是免费的吗?"
            },
            {
              "text":"哪些城市支持上门回收?"
            }
        ],
    },
    swichThirdTab:function(e){
        var that = this;
        if(that.data.thirdTab == e.target.dataset.third){
            return false;
        }else{
            that.setData({
            thirdTab:e.target.dataset.third,
            sellThirdMorestate:0
          })
        }
    },
    sellThirdMore:function(){
        let that = this;
        that.setData({
          sellThirdMorestate:1
        })
    },
    thirdOutShow:function(){
        let that = this;
        that.setData({
          thirdOutShowState:0
        })
    },
    sellThirdFixedBottomBtnOneText:function(){
        let that = this;
        that.setData({
          sellThirdFixedBottomBtnState:0
        })
    },
    swichThirdTab:function(e){
        var that = this;
        if(that.data.thirdTab == e.target.dataset.third){
          return false;
        }else{
          that.setData({
            thirdTab:e.target.dataset.third,
            sellThirdMorestate:0
          })
        }
    },
    sellThirdMore:function(){
        let that = this;
        that.setData({
          sellThirdMorestate:1
        })
    },
})
